# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monkeysmasher1's offical website
email: your-miniwolverine2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to the website, using codeacadamy.com and github I have created this free website
 for the internet to see! I'm new to this so this is just a test website, as i progress in
 adding code, I will do more with this, for now it stands as a "Dummy" website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: loganlavallee
github_username:  monkeysmasher1
twitch username: monkeysmasher_1
youtube username: monkeysmasher1: mario and anime

# Build settings
markdown: kramdown
